#!/usr/bin/env bash
# script that Install nginx web server


apt-get -y update
apt-get -y install nginx
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html;

        server_name _;

        location / {
                try_files \$uri \$uri/ =404;
        }

        location /test {
                return 200 'Hello World!';
        }
}" > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
