#!/usr/bin/env bash
#script that Install nginx web server

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
update-rc.d nginx defaults
ufw allow 'Nginx Full'
