#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "24i\    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sed -i "25i\    error_page 404 /error_404.html;" /etc/nginx/sites-available/default
sed -i "53i\            # Add custom header with the hostname of the server" /etc/nginx/sites-available/default
sed -i "54i\            add_header X-Served-By \$hostname;" /etc/nginx/sites-available/default
systemctl reload nginx
