#!/usr/bin/env bash
# Bash (init) script 101-manage_my_process that manages manage_my_process. (both files need to be pushed to git)

# Requirements:

# When passing the argument start:
# Starts manage_my_process
# Creates a file containing its PID in /var/run/my_process.pid
# Displays manage_my_process started
# When passing the argument stop:
# Stops manage_my_process
# Deletes the file /var/run/my_process.pid
# Displays manage_my_process stopped
# When passing the argument restart
# Stops manage_my_process
# Deletes the file /var/run/my_process.pid
# Starts manage_my_process
# Creates a file containing its PID in /var/run/my_process.pid
# Displays manage_my_process restarted
# Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed
SCRIPT_PATH="./manage_my_process" 

start_process() {
        $SCRIPT_PATH &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
}
stop_process() {
    if [ -f /var/run/my_process.pid ]; then
    PID=$(cat /var/run/my_process.pid)
    kill "$PID"
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
    fi
}
restart_process() {
    if [ -f /var/run/my_process.pid ]; then
        PID=$(cat /var/run/my_process.pid)
        kill "$PID"
        rm  /var/run/my_process.pid
    fi
    $SCRIPT_PATH &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"
}
case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac