#!/usr/bin/env bash
#Bash script that groups visitors by IP and HTTP status code, and displays this data.
awk '{ ip_code[$1 " " $9]++ } END { for (i in ip_code) print ip_code[i], i }' apache-access.log | sort -nr
