#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and in 9th display "Hi"
count=1;
while [ $count -le 10 ]
do
    echo "Best School"
    if [ $count -eq 9 ]
    then echo "Hi"
    fi
    ((count+=1))
done
