#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.

# Requirements:

# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/new_host
sed -i s/127.0.0.1/127.0.0.2/ ~/new_host
echo "8.8.8.8 facebook.com" >> ~/new_host
cp -f ~/new_host /etc/hosts
