#!/usr/bin/env bash
# change nginx user
pkill apache2
chmod 444 /etc/nginx/nginx.conf
sed -i "/^#user.*/c\user nginx;" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
