#!/usr/bin/env bash
# This script will connect to the server using a private key
server_address="107.23.61.147"
private_key_path="~/.ssh/school"
username="ubuntu"
ssh -i "$private_key_path" "$username@$server_address"
