#!/usr/bin/env bash
# Requirements:

# Your SSH client configuration must be configured to use the private key ~/.ssh/school
# Your SSH client configuration must be configured to refuse to authenticate using a password

Host *
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
    BatchMode yes
